### ISSUE TITLE
nil pointer dereference when parsing multiple config file

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad-autoscaler#419]
setup:

config/strategy.hcl:

```hcl
strategy "target-value" {
  driver = "target-value"
}
```

config/z_nomad.hcl:

```hcl
nomad {
  address = "http://localhost:4646"
  region  = "global"
  token   = "sometoken"
}
```

nomad-autoscaler agent -config config

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16d9b76]

goroutine 1 [running]:
github.com/hashicorp/nomad-autoscaler/agent/config.(*Nomad).merge(0x0, 0xc0003f6e70, 0x27a)
        /Users/huan/workspace/nomad-autoscaler/agent/config/config.go:448 +0x36
github.com/hashicorp/nomad-autoscaler/agent/config.(*Agent).Merge(0xc0000ca1e0, 0xc0004ae6e0, 0xc0004ae6e0)
        /Users/huan/workspace/nomad-autoscaler/agent/config/config.go:376 +0x83b
github.com/hashicorp/nomad-autoscaler/agent/config.loadDir(0x7ffeefbff431, 0x2, 0x2c5cea0, 0xc0000aa9c0, 0x0)
        /Users/huan/workspace/nomad-autoscaler/agent/config/config.go:837 +0x2a6
github.com/hashicorp/nomad-autoscaler/agent/config.Load(0x7ffeefbff431, 0x2, 0xc0000ca140, 0xc0000945d0, 0x7ffeefbff42a)
        /Users/huan/workspace/nomad-autoscaler/agent/config/config.go:797 +0x212
github.com/hashicorp/nomad-autoscaler/agent/config.LoadPaths(0xc000098400, 0x1, 0x1, 0x2, 0x0, 0x0)
        /Users/huan/workspace/nomad-autoscaler/agent/config/config.go:761 +0x105
github.com/hashicorp/nomad-autoscaler/command.(*AgentCommand).readConfig(0xc000094570, 0x70, 0x2741860, 0xc0000b0301, 0xc0000aec40)
        /Users/huan/workspace/nomad-autoscaler/command/agent.go:370 +0x12db
github.com/hashicorp/nomad-autoscaler/command.(*AgentCommand).Run(0xc000094570, 0xc000130060, 0x2, 0x2, 0x0)
        /Users/huan/workspace/nomad-autoscaler/command/agent.go:224 +0x8f
github.com/mitchellh/cli.(*CLI).Run(0xc0000c4000, 0xc000094420, 0x29ca145, 0x7)
        /Users/huan/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1cf
main.main()
        /Users/huan/workspace/nomad-autoscaler/main.go:26 +0x29b
```

**Comment by lgfa29** [comment]
Thanks for the report @fredwangwang.

I made a small change in your report to help others reproduce this error. The `nomad.hcl` file needs to be loaded last to trigger this panic.
