### ISSUE TITLE
Autoscaler keeps crashing with SIGSEGV

### ISSUE THREAD

**Issue by JanMa** [hashicorp/nomad-autoscaler#555]
I recently updated my deployments of the Nomad Autoscaler to the latest version `0.3.4`. Since then, it regularly crashes
with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa1ae86]

goroutine 41 [running]:
github.com/hashicorp/nomad-autoscaler/sdk.(*ScalingPolicy).Validate(0xc000266e90)
	/home/circleci/project/project/sdk/policy.go:68 +0x26
github.com/hashicorp/nomad-autoscaler/policy.(*Handler).Run(0xc000619c20, {0x1a22e30, 0xc000309700}, 0x0)
	/home/circleci/project/project/policy/handler.go:158 +0x61f
github.com/hashicorp/nomad-autoscaler/policy.(*Manager).Run.func1({0xc000446270, 0x24})
	/home/circleci/project/project/policy/manager.go:116 +0x46
created by github.com/hashicorp/nomad-autoscaler/policy.(*Manager).Run
	/home/circleci/project/project/policy/manager.go:115 +0xed3
```

For reference, here's my Job template I use to deploy it via Terraform:
```hcl
job "${namespace}-autoscaler" {
  datacenters = ${jsonencode(datacenters)}
  namespace = "infra"

  group "${namespace}-autoscaler" {
    count = 1

    task "${namespace}-autoscaler" {
      driver = "docker"

      resources {
        cpu    = 1024
        memory = 512
      }

      config {
        image   = "hashicorp/nomad-autoscaler:${version}"
        command = "nomad-autoscaler"
        # https://www.nomadproject.io/docs/autoscaling/cli
        args = [
          "agent",
          "-config", "local/config.hcl",
          "-log-level", "${log_level}",
          "-log-json", "true"
        ]
      }

      template {
        # https://www.nomadproject.io/docs/autoscaling/agent
        data        = <<EOF
plugin_dir = "/plugins"
nomad {
  address   = "http://{{env "attr.unique.network.ip-address" }}:4646"
  token     = "${nomad_token}"
  namespace = "${namespace}"
}
apm "nomad" {
  driver = "nomad-apm"
  config = {
    address = "http://{{env "attr.unique.network.ip-address" }}:4646"
  }
}
apm "prometheus" {
  driver = "prometheus"
  config = {
    address = "http://prometheus2.service.consul:9090"
  }
}
strategy "target-value" {
  driver = "target-value"
}
strategy "fixed-value" {
  driver = "fixed-value"
}
strategy "pass-through" {
  driver = "pass-through"
}
EOF
        destination = "local/config.hcl"
      }
    }
  }
}
```

**Comment by jrasell** [comment]
Hi @JanMa and thanks for raising this issue. I believe this has been fixed by https://github.com/hashicorp/nomad-autoscaler/pull/551 which has been merged into main but is currently unreleased. We do, however, produce nightly builds, the [latest](https://github.com/hashicorp/nomad-autoscaler/releases/tag/nightly) of which does include the fix for the issue you have encountered. If possible, could you try this build to see if your issue is resolved?

**Comment by lgfa29** [comment]
[v0.3.5](https://releases.hashicorp.com/nomad-autoscaler/0.3.5/) is out now, which should fix this problem. Give it a try and let us know how it goes 🙂 

I will close the issue for now, but we can re-open it if the issue persists.

Thank you for the report!
