### ISSUE TITLE
Datadog APM: nil pointer panic

### ISSUE THREAD

**Issue by seanamos** [hashicorp/nomad-autoscaler#602]
Version: 0.3.7

Trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd9258f]

goroutine 84 [running]:
github.com/hashicorp/nomad-autoscaler/plugins/builtin/apm/datadog/plugin.(*APMPlugin).QueryMultiple(0xc0004eed80, {0xc0000e3e00, 0x7c}, {{0xc0d24a709a5dfb47, 0xfffffff6060de406, 0x2b6dfc0}, {0xc0d24a7f9a5dfb47, 0x3fe553c06, 0x2b6dfc0}})
	github.com/hashicorp/nomad-autoscaler/plugins/builtin/apm/datadog/plugin/plugin.go:179 +0x6ef
github.com/hashicorp/nomad-autoscaler/plugins/builtin/apm/datadog/plugin.(*APMPlugin).Query(0xc0d24a709a5dfb47, {0xc0000e3e00, 0x2b6dfc0}, {{0xc0d24a709a5dfb47, 0xfffffff6060de406, 0x2b6dfc0}, {0xc0d24a7f9a5dfb47, 0x3fe553c06, 0x2b6dfc0}})
	github.com/hashicorp/nomad-autoscaler/plugins/builtin/apm/datadog/plugin/plugin.go:128 +0x65
github.com/hashicorp/nomad-autoscaler/policyeval.(*checkHandler).runAPMQuery(0xc0009301e0, {0x1e4d480, 0xc0004eed80})
	github.com/hashicorp/nomad-autoscaler/policyeval/base_worker.go:515 +0x43f
github.com/hashicorp/nomad-autoscaler/policyeval.(*checkHandler).start.func1()
	github.com/hashicorp/nomad-autoscaler/policyeval/base_worker.go:413 +0x72
created by github.com/hashicorp/nomad-autoscaler/policyeval.(*checkHandler).start
	github.com/hashicorp/nomad-autoscaler/policyeval/base_worker.go:411 +0x3d7
```

DD Query:
`max:proc.nomad_task.cpu.total_pct{env:dev,nomad_job:testing} / avg:docker.cpu.limit{env:dev,nomad_job:testing} * 100`

Example DD Response Data:
```
{
    "status": "ok",
    "resp_version": 1,
    "series": [
        {
            "end": 1667816313000,
            "attributes": {},
            "metric": "((proc.nomad_task.cpu.total_pct / docker.cpu.limit) * 100)",
            "interval": 1,
            "tag_set": [],
            "start": 1667816118000,
            "length": 47,
            "query_index": 0,
            "aggr": "max",
            "scope": "env:dev,nomad_job:testing",
            "pointlist": [
                [
                    1667816118000.0,
                    null
                ],
                [
                    1667816120000.0,
                    2.61309822400411
                ],
                [
                    1667816123000.0,
                    null
                ],
                [
                    1667816130000.0,
                    3.2824552059173584
                ],
                [
                    1667816133000.0,
                    null
                ],
                [
                    1667816138000.0,
                    null
                ],
                [
                    1667816140000.0,
                    1.9821606079737344
                ],
                [
                    1667816148000.0,
                    null
                ],
                [
                    1667816150000.0,
                    2.6441909869511924
                ],
                [
                    1667816153000.0,
                    null
                ],
                [
                    1667816160000.0,
                    3.2599836587905884
                ],
                [
                    1667816163000.0,
                    null
                ],
                [
                    1667816168000.0,
                    null
                ],
                [
                    1667816170000.0,
                    1.9753086566925049
                ],
                [
                    1667816178000.0,
                    null
                ],
                [
                    1667816180000.0,
                    1.9831432898839314
                ],
                [
                    1667816183000.0,
                    null
                ],
                [
                    1667816190000.0,
                    2.636348605155945
                ],
                [
                    1667816193000.0,
                    null
                ],
                [
                    1667816198000.0,
                    null
                ],
                [
                    1667816200000.0,
                    1.9723866383234658
                ],
                [
                    1667816208000.0,
                    null
                ],
                [
                    1667816210000.0,
                    1.9762845834096272
                ],
                [
                    1667816213000.0,
                    null
                ],
                [
                    1667816220000.0,
                    3.263175090154012
                ],
                [
                    1667816223000.0,
                    null
                ],
                [
                    1667816228000.0,
                    null
                ],
                [
                    1667816230000.0,
                    1.970443328221639
                ],
                [
                    1667816238000.0,
                    null
                ],
                [
                    1667816240000.0,
                    1.9656020402908325
                ],
                [
                    1667816243000.0,
                    null
                ],
                [
                    1667816250000.0,
                    2.64288067817688
                ],
                [
                    1667816253000.0,
                    null
                ],
                [
                    1667816258000.0,
                    null
                ],
                [
                    1667816260000.0,
                    1.9762845834096272
                ],
                [
                    1667816268000.0,
                    null
                ],
                [
                    1667816270000.0,
                    1.9870839516321817
                ],
                [
                    1667816273000.0,
                    null
                ],
                [
                    1667816280000.0,
                    4.548408190409343
                ],
                [
                    1667816283000.0,
                    null
                ],
                [
                    1667816288000.0,
                    null
                ],
                [
                    1667816290000.0,
                    1.9753086566925049
                ],
                [
                    1667816298000.0,
                    null
                ],
                [
                    1667816300000.0,
                    1.9851116339365642
                ],
                [
                    1667816303000.0,
                    null
                ],
                [
                    1667816310000.0,
                    2.6208025217056274
                ],
                [
                    1667816313000.0,
                    null
                ]
            ],
            "expression": "((max:proc.nomad_task.cpu.total_pct{env:dev,nomad_job:testing} / avg:docker.cpu.limit{env:dev,nomad_job:testing}) * 100)",
            "unit": null,
            "display_name": "((proc.nomad_task.cpu.total_pct / docker.cpu.limit) * 100)"
        }
    ],
    "to_date": 1667816316000,
    "query": "max:proc.nomad_task.cpu.total_pct{env:dev,nomad_job:testing} / avg:docker.cpu.limit{env:dev,nomad_job:testing} * 100",
    "message": "",
    "res_type": "time_series",
    "times": [],
    "from_date": 1667816113000,
    "group_by": [],
    "values": []
}
```

**Comment by lgfa29** [comment]
Thanks for the report and the query data @seanamos!

I opened #606 to fix this by skipping `null` values from query results.
